name: base
channels:
  - defaults
dependencies:
  - anaconda-client=1.7.2
  - asgiref=3.3.2
  - attrs=20.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - clyent=1.2.2
  - conda=4.10.0
  - conda-package-handling=1.7.2
  - console_shortcut=0.1.1
  - cryptography=3.2.1
  - django=3.1.7
  - idna=2.10
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - ipython_genutils=0.2.0
  - jsonschema=3.2.0
  - jupyter_core=4.7.1
  - krb5=1.17.1
  - libpq=12.2
  - menuinst=1.4.16
  - nbformat=5.1.2
  - openssl=1.1.1k
  - pip=20.2.4
  - powershell_shortcut=0.0.1
  - psycopg2=2.8.6
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2021.1
  - pywin32=227
  - pyyaml=5.4.1
  - requests=2.24.0
  - ruamel_yaml=0.15.87
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - tqdm=4.51.0
  - traitlets=5.0.5
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
